### ISSUE TITLE
YouTube link

### ISSUE THREAD

**Issue by erickDevUp** [leonardof02/example-telegram-bots#1]
Añade link del curso en el readme 🙃

**Comment by leonardof02** [comment]
El curso lo estoy subiendo de poco en poco 😅, aun no está público, cuando lo esté añado el Link 🙂

**Comment by leonardof02** [comment]
El curso lo estoy subiendo de poco en poco 😅, aun no está público, cuando lo esté añado el Link 🙂

**Comment by leonardof02** [comment]
Ya esta el link!
